apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 80        # Port exposed externally
      targetPort: 5000  # Port your container listens on
  type: LoadBalancer

